#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
# cowsay added by Jon Ellsworth <https://github.com/jonrellsworth>

NOW="$(date +%s)"

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
    if [[ -t 0 || -t 1 ]]; then
        if [ $(( $NOW % 3 )) -eq 0 ]; then
            fortune -a | cowsay -f head-in
            print
        elif [ $(( $NOW % 2 )) -eq 0 ]; then
            cowsay $(fortune -a)
            print
        else 
            fortune -a | cowsay -f tux
            print
        fi 
    fi
fi
